run:
  timeout: 5m
issues:
  fix: true
linters-settings:
  lll:
    line-length: 180
linters:
  enable-all: true
  disable:
  - gomnd
  - testpackage
  - nestif
  - gochecknoglobals
  - funlen
  - gocognit
  - cyclop
  - wrapcheck
  - varnamelen
  - execinquery
  - exhaustruct
  - musttag
  - depguard
  - ireturn