run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  - testpackage
  - nestif
  - gochecknoglobals
  - funlen
  - gocognit
  - exhaustivestruct
  - cyclop
  - wrapcheck
  - varnamelen