version: "2"
linters:
  default: all
  disable:
  - noinlineerr
  - funcorder
  - godoclint
  - err113
  - cyclop
  - depguard
  - exhaustruct
  - funlen
  - gochecknoglobals
  - gocognit
  - ireturn
  - mnd
  - musttag
  - nestif
  - testpackage
  - varnamelen
  - wrapcheck
  settings:
    lll:
      line-length: 180
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$
issues:
  fix: true
formatters:
  enable:
  - gci
  - gofmt
  - gofumpt
  - goimports
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
