run:
  timeout: 5m
issues:
  fix: true
linters:
  enable-all: true
  disable:
  # deprecated
  - deadcode
  - maligned
  - ifshort
  - golint
  - nosnakecase
  - scopelint
  - interfacer
  - structcheck
  - varcheck
  ############
  - testpackage
  - nestif
  - gochecknoglobals
  - funlen
  - gocognit
  - exhaustivestruct
  - cyclop
  - wrapcheck
  - varnamelen
  - execinquery
  - exhaustruct
  - musttag
  - depguard