dockers:
- goos: linux
  goarch: amd64
  image_templates:
  - paskalmaksim/kubernetes-manager:latest
  - paskalmaksim/kubernetes-manager:{{ .Tag }}
  build_flag_templates:
  - --build-arg=APPVERSION={{.ShortCommit}}
  extra_files:
  - front/
builds:
- dir: ./cmd/main
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -X github.com/maksim-paskal/kubernetes-manager/pkg/config.gitVersion={{.Version}}-{{.ShortCommit}}-{{.Timestamp}}
  goos:
  - linux
  goarch:
  - amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'