project_name: kubernetes-manager
release:
  footer: |
    ## Docker Images
    - `paskalmaksim/{{.ProjectName}}:latest`
    - `paskalmaksim/{{.ProjectName}}:{{.Tag}}`
dockers:
- use: buildx
  goos: linux
  goarch: amd64
  image_templates:
  - paskalmaksim/{{.ProjectName}}:latest
  - paskalmaksim/{{.ProjectName}}:{{ .Tag }}
  build_flag_templates:
  - "--build-arg=APPVERSION={{.ShortCommit}}"
  - "--platform=linux/amd64"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  extra_files:
  - front/
- use: buildx
  goos: linux
  goarch: arm64
  image_templates:
  - paskalmaksim/{{.ProjectName}}:latest
  - paskalmaksim/{{.ProjectName}}:{{.Tag}}
  build_flag_templates:
  - "--build-arg=APPVERSION={{.ShortCommit}}"
  - "--platform=linux/arm64/v8"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  extra_files:
  - front/
builds:
- dir: ./cmd/main
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -X github.com/maksim-paskal/kubernetes-manager/pkg/config.gitVersion={{.Version}}-{{.ShortCommit}}-{{.Timestamp}}
  goos:
  - linux
  goarch:
  - amd64
  - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'