#!/bin/sh

apt update
apt install -y procps $PHPIZE_DEPS

pecl install xdebug-2.9.0
docker-php-ext-enable xdebug

cp /kubernetes-manager/xdebug.ini /usr/local/etc/php/conf.d/15-xdebug.ini

pkill -USR2 -o php-fpm