apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-manager
  labels:
    app: kubernetes-manager
spec:
  selector:
    matchLabels:
      app: kubernetes-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-manager
    spec:
      serviceAccountName: kubernetes-manager
      containers:
      - name: kubernetes-manager
        resources:
{{ toYaml .Values.resources | indent 9 }}
        image: {{ .Values.registry.image }}
        imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        {{ if .Values.sentry.enabled }}
        - name: "SENTRY_DSN"
          value: {{ .Values.sentry.host }}
        {{ end }}
        command:
        - /app/kubernetes-manager
        - --front.dist=/app/dist
        {{ range .Values.args }}
        - {{ . }}
        {{ end }}
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-manager
  labels:
    app: kubernetes-manager
spec:
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
  selector:
    app: kubernetes-manager
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-manager
  labels:
    app: kubernetes-manager
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host | quote }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: kubernetes-manager
          servicePort: 9000
