registry:
  image: paskalmaksim/kubernetes-manager:latest
  imagePullPolicy: Always

createDeployment: true

replicas: 2

tolerations: []
nodeSelector: {}

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi

sentry:
  enabled: false
  host: ""

service:
  type: ClusterIP

sa:
  # create token for public access
  token: false
  annotations: {}

config:
  # aws-dev: |
  #   apiVersion: v1
  #   clusters:
  #   - cluster:
  #       certificate-authority-data: "<DATA>"
  #       server: "https://kubernetes-api"
  #     name: kubernetes-manager
  #   contexts:
  #   - context:
  #       cluster: kubernetes-manager
  #       user: kubernetes-manager
  #     name: kubernetes-manager
  #   current-context: kubernetes-manager
  #   kind: Config
  #   preferences: {}
  #   users:
  #   - name: kubernetes-manager
  #     user:
  #       token: "<TOKEN>"

  config.yaml: |
    kubernetesendpoints:
    - name: default
      kubeconfigserver: https://some-public-kubernetes-endpoint
    # - name: aws-dev
    #   kubeconfigpath: /config/aws-dev
    #   kubeconfigserver: https://aws-kubernetes-endpoint

env: {}
# - name: FRONT_SENTRY_DSN
#   value: https://id@sentry/1

args: []
# - --log.level=INFO
# - --kubeconfig.server=https://kubernetes-api
# - --gitlab.url=https://git/api/v4
# - --gitlab.token=git-token

ingress:
  enabled: false
  secretName: ""
  host: "test.com"
  annotations: {}
