apiVersion: v2
icon: https://helm.sh/img/helm.svg
name: kubernetes-manager-rbac
version: 0.0.3
description: RBAC to kubernetes-manager
maintainers:
- name: maksim-paskal  # Maksim Paskal
  email: paskal.maksim@gmail.com
