apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubernetes-manager-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["delete","patch"]
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","list","delete"]
- apiGroups: ["apps"]
  resources: ["deployments","statefulsets"]
  verbs: ["list","get","update"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["pods/exec","pods/portforward"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["list","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-manager
roleRef:
  kind: Role
  name: kubernetes-manager-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubernetes-manager
  namespace: {{ .Values.kubernetesManagerNamespace }}