version: '3'
services:
  kubernetes-manager:
    #image: paskalmaksim/kubernetes-manager:latest
    build:
      context: ../
    environment:
    - RCLONE_CONFIG_S3_TYPE=s3
    - RCLONE_CONFIG_S3_PROVIDER=AWS
    - RCLONE_CONFIG_S3_ACCESS_KEY_ID=AWS_KEY
    - RCLONE_CONFIG_S3_SECRET_ACCESS_KEY=AWS_SECRET
    - RCLONE_CONFIG_S3_REGION=eu-central-1
    - POD_NAMESPACE=kubernetes-manager
    - SYSTEM_GIT_TAGS=^master$$,^release-.*
    - SYSTEM_NAMESPACES=kube-system
    - SENTRY_ENVIRONMENT=cleanOldTags
    - SENTRY_DSN=https://id@sentry/1
    command:
    - /bin/sh
    - -c
    - |
      set -ex
      registry serve /etc/docker/registry/config.yml&
      sleep 3

      rclone --quiet sync s3:AWS_S3_BUCKET /var/lib/registry

      /app/kubernetes-manager \
      --mode=cleanOldTags \
      --registry.url="http://127.0.0.1:5000" \
      --registry.directory=/var/lib/registry/ \
      --kubeconfig.path=/opt/kubeconfig

      cat cleanOldTags.sh

      registry garbage-collect --delete-untagged /etc/docker/registry/config.yml
      rclone --quiet sync /var/lib/registry s3:AWS_S3_BUCKET
    volumes:
    - /path-to-kubeconfig:/opt/kubeconfig:ro
    - /path-to-huge-directory:/var/lib/registry/:rw
