on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
jobs:
  validate-license:
    name: validate-license
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./scripts/validate-license.sh