registry:
  image: paskalmaksim/kubernetes-manager:v0.0.3
  imagePullPolicy: IfNotPresent

resources: {}

jaeger:
  agentOnHost: false 
sentry:
  enabled: false
  host: ""

env: {}
# - name: FRONT_PHPMYADMIN_URL
#   value: https://phpmyadmin.example.com
# - name: FRONT_DEBUG_SERVER_NAME
#   value: dev.example.com
# - name: FRONT_SENTRY_DSN
#   value: https://id@sentry/1
args: []
# - --log.level=INFO
# - --kubeconfig.server=https://kubernetes-api
# - --gitlab.url=https://git/api/v4
# - --gitlab.token=git-token
# - --system.gitTags=master,release-.*
# - --system.namespaces=kube-system

ingress:
  host: "test.com"
  annotations: {}